### ISSUE TITLE
No error logging system in place

### ISSUE THREAD

**Issue by nitinpaul** [tifrh/sawaliram#16]
Set up an error logging system like Sentry to monitor crashes and fix bugs and errors as they happen. I can vouch for Sentry, but I've only worked with it in a PHP/Laravel set up. Please discuss before starting your work on this issue, especially if a free solution is not available.

**Comment by badrihippo** [comment]
Is this related to #13? What's the difference?

**Comment by nitinpaul** [comment]
I should have made this clearer. This issue is for setting up an error-monitoring system like Sentry. #13 is for enabling Django's built-in logging system. I think #13 is more important right now, we will have to decide on Sentry or whatever alternative is available.

**Comment by nitinpaul** [comment]
Closing the issue to keep all logging related discussions on #13
