### ISSUE TITLE
English translations of questions should be stored in a separate table

### ISSUE THREAD

**Issue by nitinpaul** [tifrh/sawaliram#29]
After the user submitted questions and curated/corrected and submitted by the Admins, the 'English translation of the question' column from the Excel file should be stored in a dedicated table (translated_questions) fr translations. This table will also store any translations later submitted by the Editors.

**Comment by Raul9595** [comment]
Can I work on this ?

**Comment by nitinpaul** [comment]
Go ahead @Raul9595 👍🏼
If the description seems a bit vague, here's a fresh version: 
When a user submits questions, it is handled by either `submit_questions()` or `submit_excel_sheet()`. One of the fields submitted is `question_text_english`. These two functions should save this field in a dedicated table for translated questions.
