### ISSUE TITLE
Why do views like login and signup have different 'get' and 'set' versions?

### ISSUE THREAD

**Issue by badrihippo** [tifrh/sawaliram#31]
This issue applies to both login and signup views, but I'll just take the login as an example for simplicity.

The `dashboard/views.py` file has *two* different views to handle logging in: `get_login_view` for initially displaying the login form, and `login_users` which does the rest of the processing, including re-displaying the login form if there are errors.

Is there a reason for this separation? Wouldn't it make more sense to have one single view that handles both initial and subsequent requests?

This seems especially pertinent as `login_user` displays the login form anyway, when there are errors. I don't see why it shouldn't handle it the first time too. This will help solve problems like #18 because we'll have one dedicated URL for each function, instead of a different one depending on the context.

To avoid showing an error message on the first load, we can do something like

    if request.method == 'GET':
        # return form
    elif request.method == 'POST':
        # do rest of the processing

The same applies to the signup view, which has a similar separation into `get_signup_view` and `signup_user`. If there's no special reason to separate the two, I'd recommend merging them into a single view.

**Comment by nitinpaul** [comment]
This is done to keep the code divided into simplest units (functions, classes etc) that perform a single function. The ```get_login_view()``` function returns the login page, and that's all. It does one task, and does it well. In this particular case, it may seem reasonable to combine the two functions, but the entire code is (or will eventually be) designed along this principle, and therefore it makes sense to separate these two functions. I do concede that the function names could be better. The ```get_login_view()``` function 'gets' the login page, and ```login_users()``` performs the action of logging users in.

**Comment by badrihippo** [comment]
The problem with this approach is, we're also creating multiple URLs for what are essentially the same task (albeit at different stages).

I didn't quite understand the need to divide code so much. In this case, it would basically involve a `if request.POST:` at the beginning and a slight modification to the second render line (made even simpler if we use Django form-validation). That said, maybe things will become clearer to when we get to more complex code 😛

But if we're handling the code this way, perhaps it would make sense to use something like [django-multiurl](https://github.com/raiderrobert/django-multiurl), so at least the URLs are kept consistent?

Having a single URL for all aspects of a task (`GET`, `POST`, etc.) seems to be the norm these days, so it doesn't feel write if we're doing `/login` to get the page and then `/action/login-user` to complete it. I'm arguing more about the URLs here, not the functions themselves.

**Comment by nitinpaul** [comment]
I think all the confusion comes from the URL structure, which is not good at all right now. Since we really want to talk about the URLs, I'm closing this issue and will open a new one for the URL structure. Let's discuss this a bit in Zulip.
