### ISSUE TITLE
Using Django Forms instead of handling POST data directly?

### ISSUE THREAD

**Issue by badrihippo** [tifrh/sawaliram#32]
Would it make sense to use Django's [form-building functions](https://docs.djangoproject.com/en/2.1/topics/forms/) rather than hand-coding forms into the HTML templates?

The initial setup would take a bit more effort, as we'd have to rewrite current forms in the new format, but we get in-built cleanup and validation features, which would be good to handle user data as it comes in, as well as provide reusable code and stronger security.

**Comment by nitinpaul** [comment]
Closing this issue since now that we are using the Forms functionality
