### ISSUE TITLE
Question saving does not work unless `assets/submissions` directory is present

### ISSUE THREAD

**Issue by badrihippo** [tifrh/sawaliram#35]
After ca0adda49c546896910be8455ae2488c44cf9b07, question saving fails with a "File not found" message unless a (possibly empty) directory is present at `sawaliram/assets/submissions`. This can be solved by running `mkdir assets/submissions` in the sawaliram root folder.

Ideally we should have some way to create this directory automatically—perhaps by committing an empty file in that directory to git?

Another option is to have a special `createdirectories` script which creates the necessary empty directories, including this one and the `sawaliram/logs` folder mentioned in #26.

**Comment by nitinpaul** [comment]
The [createsubmissionsfolder.py](https://github.com/tifrh/sawaliram/blob/master/dashboard/management/commands/createsubmissionsfolder.py) script does exactly that. I think we should combine all these initialisation scripts into one that sets up everything.

**Comment by badrihippo** [comment]
Ah. Then I should probably create one for `createlogsfolder.py` as well (once it's finalised).

Regarding a single initialisation script, I think it'd be better to keep them separate, and then create one "meta" script to import and run all of them. That way, we'll have more fine-grained control in case we want to run only one of the management commands without triggering the others.

Can't think of a name for that master command though: `createeverything.py` sounds a bit cheesy, I think?

**Comment by badrihippo** [comment]
Discussion moved to #36.
