### ISSUE TITLE
Footer is not updated to the new design

### ISSUE THREAD

**Issue by nitinpaul** [tifrh/sawaliram#46]
The footer needs to be updated to the new design, which can be found in the #design channel of our [Zulip server](https://sawaliram.zulipchat.com/join/eapx8841i41gyg6ildlpz2t1/). 

Main design challenge here is the wavy design. Feel free to ask questions!

Join the #design channel for the design assets and to discuss this issue!

**Comment by badrihippo** [comment]
This [SVG Wave Generator](https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections) might help...

**Comment by nitinpaul** [comment]
That looks like a very useful tool! Thanks internet! :)
