### ISSUE TITLE
Green title bar is missing on every page

### ISSUE THREAD

**Issue by nitinpaul** [tifrh/sawaliram#50]
The new design adds a green title bar at the top of the page which has the title of the page on the left and the user profile icon on the right. Clicking on the user profile icon opens the user menu.

The design of the menu and the title bar can be found in the #design channel of our [zulip server](https://sawaliram.zulipchat.com/join/eapx8841i41gyg6ildlpz2t1/).

**Comment by badrihippo** [comment]
Is this the "green title bar" you mean?

![green-bar](https://user-images.githubusercontent.com/7288084/60173783-2a2c3000-982d-11e9-8afd-5bc8cdd2836a.png)

If you send me the media files (Sawaliram logo PNG), I could do the rest.

**Comment by nitinpaul** [comment]
Yes, I'm just calling it page title bar now because it's not green everywhere. I'm attaching the default user profile logo

![sawaliram_default_user](https://user-images.githubusercontent.com/6622733/60263248-caea2080-98fd-11e9-8e1f-0f9b542e4b4c.png)
